# Generated by Django 5.1.7 on 2025-03-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='COLOR')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ITEM')),
                ('price', models.IntegerField(verbose_name='PRICE')),
                ('pic', models.ImageField(upload_to='pics/', verbose_name='PICTURE')),
                ('backpic', models.ImageField(upload_to='backpics/', verbose_name='BACK PICTURE')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothesapp.color', verbose_name='COLOR')),
            ],
            options={
                'verbose_name': 'CLOTHING',
                'verbose_name_plural': 'CLOTHES',
            },
        ),
    ]
