# Generated by Django 5.1.7 on 2025-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL')),
                ('address', models.CharField(max_length=255, verbose_name='АDDRESS')),
                ('items', models.TextField(verbose_name='ITEMS')),
                ('status', models.CharField(choices=[('processing', 'PROCESSING'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED'), ('picked_up', 'PUCKED UP')], default='processing', max_length=20, verbose_name='STATUS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATION TIME')),
            ],
            options={
                'verbose_name': 'ORDER',
                'verbose_name_plural': 'ORDERS',
            },
        ),
    ]
