# Generated by Django 5.1.7 on 2025-03-21 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=4, verbose_name='SIZE')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothesapp.clothes', verbose_name='CLOTHES')),
            ],
            options={
                'verbose_name': 'CART ITEM',
                'verbose_name_plural': 'CART ITEMS',
            },
        ),
    ]
