# Generated by Django 5.1.7 on 2025-03-24 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0002_cartitem'),
        ('clothesapp', '0002_order'),
    ]

    operations = [
    ]
